/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ParticiparRouteImport } from './routes/participar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DenunciasRouteImport } from './routes/denuncias'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteIndexRouteImport } from './routes/asistente/index'
import { Route as ProyectoIdRouteImport } from './routes/proyecto/$id'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthDashboardUsuariosRouteImport } from './routes/_auth/dashboard/usuarios'
import { Route as AuthDashboardComentariosRouteImport } from './routes/_auth/dashboard/comentarios'
import { Route as AuthDashboardProjectIdRouteImport } from './routes/_auth/dashboard/project/$id'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticiparRoute = ParticiparRouteImport.update({
  id: '/participar',
  path: '/participar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasRoute = DenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteIndexRoute = AsistenteIndexRouteImport.update({
  id: '/asistente/',
  path: '/asistente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoIdRoute = ProyectoIdRouteImport.update({
  id: '/proyecto/$id',
  path: '/proyecto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardUsuariosRoute = AuthDashboardUsuariosRouteImport.update({
  id: '/dashboard/usuarios',
  path: '/dashboard/usuarios',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardComentariosRoute =
  AuthDashboardComentariosRouteImport.update({
    id: '/dashboard/comentarios',
    path: '/dashboard/comentarios',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthDashboardProjectIdRoute = AuthDashboardProjectIdRouteImport.update({
  id: '/dashboard/project/$id',
  path: '/dashboard/project/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/dashboard/comentarios': typeof AuthDashboardComentariosRoute
  '/dashboard/usuarios': typeof AuthDashboardUsuariosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/project/$id': typeof AuthDashboardProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denuncias': typeof DenunciasRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente': typeof AsistenteIndexRoute
  '/dashboard/comentarios': typeof AuthDashboardComentariosRoute
  '/dashboard/usuarios': typeof AuthDashboardUsuariosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/project/$id': typeof AuthDashboardProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/denuncias': typeof DenunciasRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/_auth/dashboard/comentarios': typeof AuthDashboardComentariosRoute
  '/_auth/dashboard/usuarios': typeof AuthDashboardUsuariosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/project/$id': typeof AuthDashboardProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denuncias'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/proyecto/$id'
    | '/asistente/'
    | '/dashboard/comentarios'
    | '/dashboard/usuarios'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denuncias'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/proyecto/$id'
    | '/asistente'
    | '/dashboard/comentarios'
    | '/dashboard/usuarios'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/denuncias'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/proyecto/$id'
    | '/asistente/'
    | '/_auth/dashboard/comentarios'
    | '/_auth/dashboard/usuarios'
    | '/api/auth/$'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DenunciasRoute: typeof DenunciasRoute
  LoginRoute: typeof LoginRoute
  ParticiparRoute: typeof ParticiparRoute
  ProyectosRoute: typeof ProyectosRoute
  ProyectoIdRoute: typeof ProyectoIdRoute
  AsistenteIndexRoute: typeof AsistenteIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participar': {
      id: '/participar'
      path: '/participar'
      fullPath: '/participar'
      preLoaderRoute: typeof ParticiparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias': {
      id: '/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof DenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/': {
      id: '/asistente/'
      path: '/asistente'
      fullPath: '/asistente/'
      preLoaderRoute: typeof AsistenteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto/$id': {
      id: '/proyecto/$id'
      path: '/proyecto/$id'
      fullPath: '/proyecto/$id'
      preLoaderRoute: typeof ProyectoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/usuarios': {
      id: '/_auth/dashboard/usuarios'
      path: '/dashboard/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof AuthDashboardUsuariosRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/comentarios': {
      id: '/_auth/dashboard/comentarios'
      path: '/dashboard/comentarios'
      fullPath: '/dashboard/comentarios'
      preLoaderRoute: typeof AuthDashboardComentariosRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/project/$id': {
      id: '/_auth/dashboard/project/$id'
      path: '/dashboard/project/$id'
      fullPath: '/dashboard/project/$id'
      preLoaderRoute: typeof AuthDashboardProjectIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardComentariosRoute: typeof AuthDashboardComentariosRoute
  AuthDashboardUsuariosRoute: typeof AuthDashboardUsuariosRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardProjectIdRoute: typeof AuthDashboardProjectIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardComentariosRoute: AuthDashboardComentariosRoute,
  AuthDashboardUsuariosRoute: AuthDashboardUsuariosRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardProjectIdRoute: AuthDashboardProjectIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DenunciasRoute: DenunciasRoute,
  LoginRoute: LoginRoute,
  ParticiparRoute: ParticiparRoute,
  ProyectosRoute: ProyectosRoute,
  ProyectoIdRoute: ProyectoIdRoute,
  AsistenteIndexRoute: AsistenteIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
