/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ParticiparRouteImport } from './routes/participar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AsistenteIndexRouteImport } from './routes/asistente/index'
import { Route as ProyectoIdRouteImport } from './routes/proyecto/$id'
import { Route as DashboardUsuariosRouteImport } from './routes/dashboard/usuarios'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticiparRoute = ParticiparRouteImport.update({
  id: '/participar',
  path: '/participar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteIndexRoute = AsistenteIndexRouteImport.update({
  id: '/asistente/',
  path: '/asistente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoIdRoute = ProyectoIdRouteImport.update({
  id: '/proyecto/$id',
  path: '/proyecto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsuariosRoute = DashboardUsuariosRouteImport.update({
  id: '/dashboard/usuarios',
  path: '/dashboard/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente': typeof AsistenteIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/participar': typeof ParticiparRoute
  '/proyectos': typeof ProyectosRoute
  '/dashboard/usuarios': typeof DashboardUsuariosRoute
  '/proyecto/$id': typeof ProyectoIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/dashboard/usuarios'
    | '/proyecto/$id'
    | '/asistente/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/dashboard/usuarios'
    | '/proyecto/$id'
    | '/asistente'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/participar'
    | '/proyectos'
    | '/dashboard/usuarios'
    | '/proyecto/$id'
    | '/asistente/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParticiparRoute: typeof ParticiparRoute
  ProyectosRoute: typeof ProyectosRoute
  DashboardUsuariosRoute: typeof DashboardUsuariosRoute
  ProyectoIdRoute: typeof ProyectoIdRoute
  AsistenteIndexRoute: typeof AsistenteIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participar': {
      id: '/participar'
      path: '/participar'
      fullPath: '/participar'
      preLoaderRoute: typeof ParticiparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/': {
      id: '/asistente/'
      path: '/asistente'
      fullPath: '/asistente/'
      preLoaderRoute: typeof AsistenteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto/$id': {
      id: '/proyecto/$id'
      path: '/proyecto/$id'
      fullPath: '/proyecto/$id'
      preLoaderRoute: typeof ProyectoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/usuarios': {
      id: '/dashboard/usuarios'
      path: '/dashboard/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof DashboardUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParticiparRoute: ParticiparRoute,
  ProyectosRoute: ProyectosRoute,
  DashboardUsuariosRoute: DashboardUsuariosRoute,
  ProyectoIdRoute: ProyectoIdRoute,
  AsistenteIndexRoute: AsistenteIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
